name: test

on:
  - push
  - pull_request

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
        gemfile:
          - rails_6.1.gemfile
          - rails_7.0.gemfile
          - rails_7.1.gemfile
          - rails_7.2.gemfile
          - rails_8.0.gemfile
        exclude:
          - gemfile: rails_8.0.gemfile
            ruby: "3.1"
          - gemfile: rails_8.0.gemfile
            ruby: "3.0"
          - gemfile: rails_8.0.gemfile
            ruby: "2.7"
          - gemfile: rails_7.2.gemfile
            ruby: "3.0"
          - gemfile: rails_7.2.gemfile
            ruby: "2.7"
      fail-fast: False

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get install --quiet --yes libsqlite3-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: |
          bundle exec rspec --color --format documentation

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: test

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: True

      - run: bundle exec rubocop --parallel --color
